---
- hosts: all
  become: yes
  task: 
  - name: i want to install apache2
    apt:
      name: apache2
      state: present

  - name: i want to start apache2
    apt:
      name: apache2
      state: restarted